---
title: "Gorilla_v11_Analysis"
output: html_document
date: "2024-08-07"
---

##--------Load packages---------
```{r setup, include=FALSE}
if (!(require("tidyverse"))) install.packages("tidyverse"); require("tidyverse")
if (!(require("psych"))) install.packages("psych"); require("psych")
if (!require("irr")) {install.packages("irr"); require("irr")} 
if (!require("reshape2")) {install.packages("reshape2"); require("reshape2")} 
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")} 
```

#---------Load in data--------
```{r}

v11 <- read.csv("../data/rating-task/data_exp_169297-v11_task-6dig.csv")

```

```{r}

granularity_data <- v11 %>%
  filter(Response.Type == "response") %>% 
  select("Participant.Public.ID","Response","Object.Name", "Spreadsheet..Image", "Spreadsheet..Audio") %>%
  mutate(Response = as.numeric(Response))

## Separating by picture vs music, removing practice stims
granularity_pic <- granularity_data %>%
  filter(Spreadsheet..Image != "") %>%
  filter(Spreadsheet..Image != "Coffee 1.jpg") %>%
  select(-c("Spreadsheet..Audio"))

granularity_music <- granularity_data %>%
  filter(Spreadsheet..Audio != "") %>%
  filter(Spreadsheet..Audio != "8_pieceA_dreamy_calm_joyous_1.mp3") %>%
  select(-c("Spreadsheet..Image"))
```

##-----Subsetting by valence and stimulus type--------
```{r}
# List of emotions
neg_emotions <- c("Angry", "Sad", "Scared", "Anxious", "Upset")
pos_emotions <- c("Happy", "Satisfied", "Excited", "Joyful", "Relaxed")

# Function to filter and rename
filter_and_rename <- function(data, emotion, media_type, keep_id = FALSE) {
  columns_to_select <- if (keep_id) {
    c("Participant.Public.ID", "Response")
  } else {
    c("Response")
  }
  
  data %>%
    filter(Object.Name == paste(emotion, "Slider")) %>%
    select(-c(paste0("Spreadsheet..", media_type), "Object.Name")) %>%
    select(all_of(columns_to_select)) %>%
    rename(!!tolower(emotion) := "Response")
}

# Apply function to each emotion for music and images
filtered_music_neg <- lapply(seq_along(neg_emotions), function(i) {
  filter_and_rename(granularity_music, neg_emotions[i], "Audio", keep_id = (i == 1))
})

filtered_music_pos <- lapply(seq_along(pos_emotions), function(i) {
  filter_and_rename(granularity_music, pos_emotions[i], "Audio", keep_id = (i == 1))
})

filtered_pic_neg <- lapply(seq_along(neg_emotions), function(i) {
  filter_and_rename(granularity_pic, neg_emotions[i], "Image", keep_id = (i == 1))
})

filtered_pic_pos <- lapply(seq_along(pos_emotions), function(i) {
  filter_and_rename(granularity_pic, pos_emotions[i], "Image", keep_id = (i == 1))
})

music_negative <- bind_cols(filtered_music_neg) %>%
  na.omit()

music_positive <- bind_cols(filtered_music_pos)

pic_negative <- bind_cols(filtered_pic_neg)

pic_positive <- bind_cols(filtered_pic_pos)

```

##----Scoring ICC------
```{r}
# Function to compute ICC and store results
compute_icc <- function(data_list, result_column) {
  sapply(seq_along(data_list), function(i) {
    icc_result <- data_list[[i]] %>%
      select(-Participant.Public.ID) %>%
      icc(model = "twoway", type = "consistency", unit = "average")
    1 - icc_result$value
  })
}

# Create a list of data frames split by Participant.Public.ID
music_negative_list <- split(music_negative, music_negative$Participant.Public.ID)
music_positive_list <- split(music_positive, music_positive$Participant.Public.ID)
pic_negative_list <- split(pic_negative, pic_negative$Participant.Public.ID)
pic_positive_list <- split(pic_positive, pic_positive$Participant.Public.ID)

# Initialize results DataFrame
results <- expand.grid(ID = names(music_negative_list))

# Compute ICC values for each subset and add to results
results$negmusicICC <- compute_icc(music_negative_list, "negmusicICC")
results$posmusicICC <- compute_icc(music_positive_list, "posmusicICC")
results$negpicICC <- compute_icc(pic_negative_list, "negpicICC")
results$pospicICC <- compute_icc(pic_positive_list, "pospicICC")

# Display the result
results
```

##--Plotting means of emotion word ratings--
```{r}
# music neg
music_negative_summary <- music_negative %>%
  select(-Participant.Public.ID) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  summarize(
    mean_value = mean(value, na.rm = TRUE),
    se_value = sd(value, na.rm = TRUE) / sqrt(n())
  )

music_negative_means <- ggplot(music_negative_summary, aes(x = variable, y = mean_value)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value), width = 0.2) +
  labs(title = "Gorilla Music Negative Emotion Means", x = "Emotion", y = "Mean") +
  theme_bw()

ggsave('../results/rating-task/v11_Music_Negative_Means_8_11_24.png', music_negative_means, width = 9)

# music pos
music_positive_summary <- music_positive %>%
  select(-Participant.Public.ID) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  summarize(
    mean_value = mean(value, na.rm = TRUE),
    se_value = sd(value, na.rm = TRUE) / sqrt(n())
  )

music_positive_means <- ggplot(music_positive_summary, aes(x = variable, y = mean_value)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value), width = 0.2) +
  labs(title = "Gorilla Music Positive Emotion Means", x = "Emotion", y = "Mean") +
  theme_bw()

ggsave('../results/rating-task/v11_Music_Positive_Means_8_11_24.png', music_positive_means, width = 9)

# pic pos
pic_positive_summary <- pic_positive %>%
  select(-Participant.Public.ID) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  summarize(
    mean_value = mean(value, na.rm = TRUE),
    se_value = sd(value, na.rm = TRUE) / sqrt(n())
  )

pic_positive_means <- ggplot(pic_positive_summary, aes(x = variable, y = mean_value)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value), width = 0.2) +
  labs(title = "Gorilla Picture Positive Emotion Means", x = "Emotion", y = "Mean") +
  theme_bw()

ggsave('../results/rating-task/v11_Picture_Positive_Means_8_11_24.png', pic_positive_means, width = 9)

# pic neg
pic_negative_summary <- pic_negative %>%
  select(-Participant.Public.ID) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  summarize(
    mean_value = mean(value, na.rm = TRUE),
    se_value = sd(value, na.rm = TRUE) / sqrt(n())
  )

pic_negative_means <- ggplot(pic_negative_summary, aes(x = variable, y = mean_value)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value), width = 0.2) +
  labs(title = "Gorilla Picture Negative Emotion Means", x = "Emotion", y = "Mean") +
  theme_bw()

ggsave('../results/rating-task/v11_Picture_Negative_Means_8_11_24.png', pic_negative_means, width = 9)
```

##--Graphs printed together to have scale reference--
```{r}
music_negative_summary$type <- "Music"
music_positive_summary$type <- "Music"
pic_negative_summary$type <- "Picture"
pic_positive_summary$type <- "Picture"
neg_summary <- bind_rows(music_negative_summary, pic_negative_summary)
pos_summary <- bind_rows(music_positive_summary, pic_positive_summary)

# Plot for negative emotions
neg_plot <- ggplot(neg_summary, aes(x = variable, y = mean_value, color = type, ymin = 0)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value), 
                width = 0.2) +
  labs(title = "Negative Emotion Means", x = "Emotion", y = "Mean") +
  theme_bw()

# Plot for positive emotions
pos_plot <- ggplot(pos_summary, aes(x = variable, y = mean_value, color = type, ymin = 0)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value), 
                width = 0.2) +
  labs(title = "Positive Emotion Means", x = "Emotion", y = "Mean") +
  theme_bw()

# Save the plots
ggsave('../results/rating-task/v11_Negative_Emotion_Means_8_11_24.png', neg_plot, width = 9)
ggsave('../results/rating-task/v11_Positive_Emotion_Means_8_11_24.png', pos_plot, width = 9)


```

##-Percent of nonzero responses--
```{r}
library(knitr)
library(readr)
library(gridExtra)
library(grid)
library(png)

# Function to calculate the percentage of non-zero responses for each column
calculate_non_zero_percentage <- function(df) {
  df %>%
    select(-Participant.Public.ID) %>%
    summarise(across(everything(), ~ round(sum(!is.na(.) & . != 0) / sum(!is.na(.)) * 100)))
}

# Calculate percentages and create tables
tables <- list(
  list(data = music_negative, caption = "% of Non-Zero Responses for Negative Emotion Words (Music)"),
  list(data = pic_negative, caption = "% of Non-Zero Responses for Negative Emotion Words (Pictures)"),
    list(data = music_positive, caption = "% of Non-Zero Responses for Positive Emotion Words (Music)"),
  list(data = pic_positive, caption = "% of Non-Zero Responses for Positive Emotion Words (Pictures)")
)

# Create grobs for each table and caption
table_grobs <- lapply(tables, function(tbl) {
  percentages <- calculate_non_zero_percentage(tbl$data)
  table_grob <- tableGrob(percentages, theme = ttheme_minimal())
  caption_grob <- textGrob(tbl$caption, gp = gpar(fontsize = 10))
  arrangeGrob(caption_grob, table_grob, ncol = 1)
})

# Arrange all tables vertically
arranged_tables <- do.call(arrangeGrob, c(table_grobs, ncol = 1))

# Save the arranged tables as a PNG file
png("../results/rating-task/v11_emotion_response_percentages_8_11_24.png", width = 400, height = 400)
grid.draw(arranged_tables)
dev.off()
```


##--Separating pics and music by valence (pos/neg)--
```{r}
pos_pic <- c("Beach 1.jpg", "Cat 5.jpg", "Fireworks 6.jpg", "Lake 12.jpg", "Rainbow 2.jpg", "Clean 1.jpg", "Cups 3.jpg", "Heart 3.jpg", "Rocks 1.jpg", "Snow 1.jpg")
pos_pic_data <- granularity_pic %>%
  filter(Spreadsheet..Image %in% pos_pic)

neg_pic <- c("Cockroach 3.jpg", "Dirt 1.jpg", "Ferret 1.jpg", "Fire 10.jpg", "Flood 1.jpg", "Garbage dump 2.jpg", "Destruction 2.jpg", "Garbage dump 1.jpg", "Prison 2.jpg", "Toilet 4.jpg")
neg_pic_data <- granularity_pic %>%
  filter(Spreadsheet..Image %in% neg_pic)

pos_music <- c("3_pieceB_joyous_anxious_sad_5.mp3", "6_pieceB_anxious_calm_joyous_8.mp3", "7_pieceB_joyous_anxious_sad_5.mp3", "7_pieceB_joyous_anxious_sad_6.mp3", "5_pieceB_calm_sad_anxious_7.mp3", "6_pieceB_anxious_calm_joyous_5.mp3", "6_pieceB_anxious_calm_joyous_7.mp3", "12_pieceA_joyous_sad_anxious_2.mp3", "12_pieceA_joyous_sad_anxious_3.mp3", "12_pieceA_joyous_sad_anxious_9.mp3")
pos_music_data <- granularity_music %>%
  filter(Spreadsheet..Audio %in% pos_music)

neg_music <- c("3_pieceB_joyous_anxious_sad_1.mp3", "11_pieceA_calm_anxious_sad_4.mp3", "11_pieceA_calm_anxious_sad_5.mp3", "11_pieceA_calm_anxious_sad_6.mp3", "11_pieceA_calm_anxious_sad_8.mp3", "5_pieceB_calm_sad_anxious_1.mp3", "5_pieceB_calm_sad_anxious_2.mp3", "5_pieceB_calm_sad_anxious_3.mp3", "5_pieceB_calm_sad_anxious_9.mp3", "11_pieceA_calm_anxious_sad_2.mp3")
neg_music_data <- granularity_music %>%
  filter(Spreadsheet..Audio %in% neg_music)
```

```{r}
# 10 clips
averages_pos_music <- pos_music_data %>%
  group_by(Spreadsheet..Audio) %>%
  summarise(
    Average.Response = mean(Response, na.rm = TRUE),
    se_value = sd(Response, na.rm = TRUE) / sqrt(n())
    )

# 10 clips
averages_neg_music <- neg_music_data %>%
  group_by(Spreadsheet..Audio) %>%
  summarise(
    Average.Response = mean(Response, na.rm = TRUE),
    se_value = sd(Response, na.rm = TRUE) / sqrt(n())
    )

# 10 pics
averages_pos_pic <- pos_pic_data %>%
  group_by(Spreadsheet..Image) %>%
  summarise(
    Average.Response = mean(Response, na.rm = TRUE),
    se_value = sd(Response, na.rm = TRUE) / sqrt(n())
    )

# 10 pics
averages_neg_pic <- neg_pic_data %>%
  group_by(Spreadsheet..Image) %>%
  summarise(
    Average.Response = mean(Response, na.rm = TRUE),
    se_value = sd(Response, na.rm = TRUE) / sqrt(n())
    )

all_averages <- bind_rows(
  averages_pos_music %>% mutate(Type = "pos_music"),
  averages_neg_music %>% mutate(Type = "neg_music"),
  averages_pos_pic %>% mutate(Type = "pos_pic"),
  averages_neg_pic %>% mutate(Type = "neg_pic"),
)

min_values <- all_averages %>%
  group_by(Type) %>%
  slice_min(Average.Response, n = 2) %>%
  ungroup()

library(ggrepel)

all_stims_plotted <- ggplot(all_averages, aes(x = Type, y = Average.Response)) +
  geom_point() +
  geom_text_repel(
    data = min_values, 
    aes(label = ifelse(is.na(Spreadsheet..Audio), Spreadsheet..Image, Spreadsheet..Audio)), 
    size = 3, 
    color = "red"
  ) +
  labs(title = "All Stims Response Averages", x = "Valence/Stimulus Type", y = "Mean Response") +
  theme_bw()

ggsave('../results/rating-task/v11_All_Stims_Means_8_11_24.png', all_stims_plotted, width = 14)

library(RColorBrewer)

all_stims_plotted <- ggplot(all_averages, aes(x = Type, y = Average.Response, color = Average.Response)) +
  geom_point() +
  geom_errorbar(aes(ymin = Average.Response - se_value, ymax = Average.Response + se_value, color = Average.Response), alpha = 0.4, width = 0.2) +
  scale_color_viridis_c()
  labs(title = "All Stims Response Averages", x = "Valence/Stimulus Type", y = "Mean Response") +
  theme_bw()

ggsave('../results/rating-task/v11_All_Stims_Means_8_11_24_Error_Bars.png', all_stims_plotted, width = 10)

```

##Recoding scores above 1 as 1
```{r}
results[, 2:5] <- lapply(df[, 2:5], function(x) ifelse(x > 1, 1, x))

```
# if i hypothetically got rid of that one major outlier
```{r}
# results <- results[-4, ]

```

##Plotting some things
```{r}
# Reshape data for both histograms
df_long1 <- results %>% gather(key = "Variable", value = "Value", negmusicICC, negpicICC)
df_long2 <- results %>% gather(key = "Variable", value = "Value", posmusicICC, pospicICC)

# Create and print histograms
negICChist <- ggplot(df_long1, aes(x = Value, fill = Variable)) +
  geom_histogram(position = "identity", alpha = 0.5) +
  labs(title = "Overlay of Negative Granularity Scores (1 - ICC)", x = "Granularity Score", y = "Count")
ggsave('../results/rating-task/Negative ICCs 8_11_24.png', negICChist, width = 14)

posICChist <- ggplot(df_long2, aes(x = Value, fill = Variable)) +
  geom_histogram(position = "identity", alpha = 0.5) +
  labs(title = "Overlay of Positive Granularity Scores (1 - ICC", x = "Granularity Score", y = "Count")
ggsave('../results/rating-task/Positive ICCs 8_11_24.png', posICChist, width = 14)

pos_graph <- ggplot(data = results, aes(x = pospicICC, y = posmusicICC)) +
  geom_point() +
  stat_smooth(method = 'lm') +
  xlab('Positive Picture Emotion Granularity') +
  ylab('Positive Music Emotion Granularity') +
  theme_classic() +
  theme(axis.title.x = element_text(size=14, face='bold'), axis.title.y = element_text(size=14, face='bold'), axis.text.x = element_text(size=12), axis.text.y = element_text(size=12))

ggsave('../results/rating-task/Pos_Graph 8_11_24.png', pos_graph, width = 9)

neg_graph <- ggplot(data = results, aes(x = negpicICC, y = negmusicICC)) +
  geom_point() +
  stat_smooth(method = 'lm') +
  xlab('Negative Picture Emotion Granularity') +
  ylab('Negative Music Emotion Granularity') +
  theme_classic() +
  theme(axis.title.x = element_text(size=14, face='bold'), axis.title.y = element_text(size=14, face='bold'), axis.text.x = element_text(size=12), axis.text.y = element_text(size=12))

ggsave('../results/rating-task/Neg_Graph 8_11_24.png', neg_graph, width = 9)

```