---
title: "OASIS_selection"
output: html_document
date: "2024-03-29"
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r}
OASIS <- read.csv(file='../stimuli/oasis/OASIS.csv')
```

#filtering
```{r}
OASIS_clean <-
  OASIS %>%
  dplyr::filter(Category != "Person")

OASIS_clean$Valence_SE <- OASIS_clean$Valence_SD/(sqrt(OASIS_clean$Valence_N))

OASIS_clean$Arousal_SE <- OASIS_clean$Arousal_SD/(sqrt(OASIS_clean$Arousal_N))

ggplot(data=OASIS_clean, aes(x=Arousal_mean, y=Valence_mean))+
  geom_point() +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red")


OASIS_cleanpospos <- 
  OASIS_clean %>%
  dplyr::filter(Arousal_mean - Arousal_SE > 3.5) %>%
  dplyr::filter(Valence_mean - Valence_SE > 3.5)

OASIS_cleanpospos$quad <-"Positive Valence, High Arousal"

ggplot(data=OASIS_cleanpospos, aes(x=Arousal_mean, y=Valence_mean))+
  geom_point() +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red")

OASIS_cleannegpos <- 
  OASIS_clean %>%
  dplyr::filter(Arousal_mean + Arousal_SE < 3.5) %>%
  dplyr::filter(Valence_mean - Valence_SE > 3.5)

OASIS_cleannegpos$quad <-"Positive Valence, Low Arousal"

ggplot(data=OASIS_cleannegpos, aes(x=Arousal_mean, y=Valence_mean))+
  geom_point() +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red")

OASIS_cleannegneg <- 
  OASIS_clean %>%
  dplyr::filter(Arousal_mean + Arousal_SE < 3.5) %>%
  dplyr::filter(Valence_mean + Valence_SE < 3.5)

OASIS_cleannegneg$quad <-"Negative Valence, Low Arousal"


ggplot(data=OASIS_cleannegneg, aes(x=Arousal_mean, y=Valence_mean))+
  geom_point() +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red")

OASIS_cleanposneg <- 
  OASIS_clean %>%
  dplyr::filter(Arousal_mean - Arousal_SE > 3.5) %>%
  dplyr::filter(Valence_mean + Valence_SE < 3.5)

OASIS_cleanposneg$quad <-"Negative Valence, High Arousal"

ggplot(data=OASIS_cleanposneg, aes(x=Arousal_mean, y=Valence_mean))+
  geom_point() +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red")

stim_selection <- 
  rbind(OASIS_cleannegneg, OASIS_cleannegpos, OASIS_cleanposneg, OASIS_cleanpospos) %>%
  dplyr::select(Theme, quad)

write.csv(file='../stimuli/OASIS_initialstims.csv', stim_selection)
```

#try more stringent thresholds for positive valence, will filter based on appropriateness for negative
```{r}
filtered <- read.csv(file='../stimuli/OASIS_initialstims.csv')

updated <- merge(filtered, OASIS_clean, by="Theme") %>%
  select(Theme, Arousal_mean, Arousal_SE, Valence_mean, Valence_SE)

updated_cleanpospos <- 
  updated %>%
  dplyr::filter(Arousal_mean - Arousal_SE > 4.5) %>%
  dplyr::filter(Valence_mean - Valence_SE > 4.5)

updated_cleanpospos$quad <-"Positive Valence, High Arousal"

updated_cleannegpos <- 
  updated %>%
  dplyr::filter(Arousal_mean + Arousal_SE < 3) %>%
  dplyr::filter(Valence_mean - Valence_SE > 4.5)

updated_cleannegpos$quad <-"Positive Valence, Low Arousal"

pos_stim_selection1 <- 
  rbind(updated_cleanpospos, updated_cleannegpos) %>%
  dplyr::select(Theme, quad)

write.csv(file='../stimuli/OASIS_filteredpos.csv', pos_stim_selection1)
```

```{r}
selected <- read.csv(file='../stimuli/oasis/selected_stims/selected_stims.csv')
# 8 high A high V
# 18 low A high V
# 14 high A low V
# 8 low A low V

selected_OASIS <- merge(selected, OASIS, by = 'Theme')
selected_OASIS$upper_arousal <- selected_1$Arousal_mean + selected_1$Arousal_SD
selected_OASIS$lower_arousal <- selected_1$Arousal_mean - selected_1$Arousal_SD
selected_OASIS$upper_valence <- selected_1$Valence_mean + selected_1$Valence_SD
selected_OASIS$lower_valence <- selected_1$Valence_mean - selected_1$Valence_SD

ggplot(data=selected_OASIS, aes(x=Arousal_mean, y=Valence_mean, label=Theme))+
  geom_point() +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red") +
  geom_errorbar(alpha=0.5, aes(ymin = lower_valence, ymax = upper_valence)) +
  geom_errorbarh(alpha=0.5, aes(xmin = lower_arousal, xmax = upper_arousal)) +
  geom_text()

selected_OASIS_pos <- subset(selected_OASIS, !(lower_valence <= 3.5))

selected_OASIS_neg <- subset(selected_OASIS, !(upper_valence >= 4.7))

# low V make sure upper limit is below 3.5
# high V make sure lower limit is above 3.5
# if not 10 stimuli left, rank order the means and take the top 10 of each valence
# OR top 5 of each quadrant
  
```

```{r}
final_OASIS <- read.csv(file='../stimuli/oasis/selected_stims/oasis_stims_tracking.csv')
selected_OASIS_final <- merge(final_OASIS, selected_OASIS, by = 'Theme')

ggplot(data=selected_OASIS_final, aes(x=Arousal_mean, y=Valence_mean, label=Theme))+
  geom_point(aes(color=quad)) +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red") +
  geom_errorbar(alpha=0.5, aes(ymin = lower_valence, ymax = upper_valence, color=quad)) +
  geom_errorbarh(alpha=0.5, aes(xmin = lower_arousal, xmax = upper_arousal, color=quad)) +
  geom_text() +
  xlab('Arousal') + ylab('Valence')

ggplot(data=selected_OASIS_final, aes(x=Arousal_mean, y=Valence_mean, label=Theme))+
  geom_point(aes(color=quad)) +
  geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
  geom_hline(yintercept = 3.5, linetype="dashed", color="red") +
  geom_errorbar(alpha=0.5, aes(ymin = lower_valence, ymax = upper_valence, color=quad)) +
  geom_errorbarh(alpha=0.5, aes(xmin = lower_arousal, xmax = upper_arousal, color=quad)) +
  geom_text() +
  xlab('Arousal') + ylab('Valence')

# Loop through each unique value in the "quad" column
for (quad_value in unique(selected_OASIS_final$quad)) {
  # Filter the data for the current quadrant
  quad_data <- subset(selected_OASIS_final, quad == quad_value)
  
  # Create the plot
  p <- ggplot(data=quad_data, aes(x=Arousal_mean, y=Valence_mean, label=Theme)) +
    geom_point() +
    geom_vline(xintercept = 3.5, linetype="dashed", color="red") +
    geom_hline(yintercept = 3.5, linetype="dashed", color="red") +
    geom_errorbar(alpha=0.5, aes(ymin = lower_valence, ymax = upper_valence, color=quad)) +
    geom_errorbarh(alpha=0.5, aes(xmin = lower_arousal, xmax = upper_arousal, color=quad)) +
    geom_text() +
    xlab('Arousal') + ylab('Valence') +
    ggtitle(paste("Quad:", quad_value))
  
  # Print the plot to display it in the console
  print(p)
}

```