---
title: "adult_online_surveyscoring"
output:
  pdf_document: default
  html_document: default
date: "2025-12-19"
---

```{r}
install.packages("corrplot")
library(tidyverse)
source("reverseCode.R")
```

```{r}
demo <- read.csv("~/Desktop/prolific_demographic_export_694574e84a79b38d198a03cb (3).csv") %>%
  subset(Status == "APPROVED")

survey <- read.csv('../data/adult_online/emo_granularity_adultonline_December 29, 2025_16.35.csv')

IDs <- read.csv('../data/adult_online/qual_task_link.csv')
IDs <- IDs[rowSums(IDs == "" | is.na(IDs)) != ncol(IDs), ]

survey <- merge(survey,IDs,by="ResponseId",all.y = TRUE)

```

#CDRISC
```{r}
CD.RISC <- survey %>%
  dplyr::select("CD.RISC1_1":"CD.RISC10_1")

CD.RISC <- as.data.frame(lapply(CD.RISC[,], as.integer)) %>%
  drop_na()

survey$CD.RISC_total <- apply(CD.RISC,1,sum)
hist(survey$CD.RISC_total)
```

#STAI-T
```{r}
STAI_T <- survey %>%
  dplyr::select("STAI1_1":"STAI20_1")

STAI_T <- as.data.frame(lapply(STAI_T[,], as.integer)) %>%
  drop_na()

cols_reverse <- c("STAI1_1","STAI3_1","STAI6_1","STAI7_1","STAI10_1","STAI13_1","STAI14_1","STAI16_1","STAI19_1")
STAI_T[cols_reverse] <- lapply(STAI_T[cols_reverse], reverseCode, min=1, max=4)

survey$STAI_total <- apply(STAI_T,1,sum)
```

#STAI-S
```{r}
STAI_S <- survey %>%
  dplyr::select("STAI.S_1_1":"STAI.S_20_1")

STAI_S <- as.data.frame(lapply(STAI_S[,], as.integer)) %>%
  drop_na()

cols_reverse <- c("STAI.S_1_1","STAI.S_2_1","STAI.S_5_1","STAI.S_8_1","STAI.S_10_1","STAI.S_11_1","STAI.S_15_1","STAI.S_16_1","STAI.S_19_1","STAI.S_20_1")
STAI_S[cols_reverse] <- lapply(STAI_S[cols_reverse], reverseCode, min=1, max=4)

survey$STAI_S_total <- apply(STAI_S,1,sum)
```

#BDI
```{r}
BDI <- survey %>%
  dplyr::select("BDI_1":"BDI_20")

BDI$BDI_15[BDI$BDI_15 == 3] <- 2
BDI$BDI_15[BDI$BDI_15 == 4 | BDI$BDI_15 == 5] <- 3
BDI$BDI_15[BDI$BDI_15 == 6 | BDI$BDI_15 == 7] <- 4

BDI$BDI_17[BDI$BDI_17 == 3] <- 2
BDI$BDI_17[BDI$BDI_17 == 4 | BDI$BDI_17 == 5] <- 3
BDI$BDI_17[BDI$BDI_17 == 6 | BDI$BDI_17 == 7] <- 4

BDI[BDI == 1] <- 0
BDI[BDI == 2] <- 1
BDI[BDI == 3] <- 2
BDI[BDI == 4] <- 3

BDI <- as.data.frame(lapply(BDI[,], as.integer))

survey$BDI_total <- apply(BDI,1,sum)
hist(survey$BDI_total)
```

#SCAARED
```{r}
scaared <- survey %>%
  dplyr::select("SCAARED1_1":"SCAARED44_1") 

scaared <- as.data.frame(lapply(scaared[,], as.integer)) %>%
  drop_na() #get subscales

survey$SCAARED_total <- apply(scaared,1,sum)
```

#PMERQ
```{r}
PMERQ <- survey %>%
  dplyr::select("PMERQ_1_1":"PMERQ_45_1")

PMERQ <- as.data.frame(lapply(PMERQ[,], as.integer)) %>%
  drop_na()

cols_conf_unpl_sit <- c("PMERQ_9_1" ,
"PMERQ_11_1" ,
"PMERQ_15_1" ,
"PMERQ_28_1")

cols_av_unpl_sit <- c("PMERQ_4_1" ,
"PMERQ_5_1" ,
"PMERQ_12_1" ,
"PMERQ_18_1",
"PMERQ_42_1" ,
"PMERQ_44_1" )

cols_res_conf <- c("PMERQ_6_1" ,
"PMERQ_17_1" ,
"PMERQ_19_1" ,
"PMERQ_26_1",
"PMERQ_36_1" ,
"PMERQ_39_1" )

cols_av_conf <- c("PMERQ_3_1" ,
"PMERQ_10_1" ,
"PMERQ_14_1" ,
"PMERQ_37_1",
"PMERQ_43_1")

cols_foc_ew <- c("PMERQ_2_1" ,
"PMERQ_22_1" ,
"PMERQ_23_1" ,
"PMERQ_31_1")

cols_cog_dis <- c("PMERQ_13_1" ,
"PMERQ_27_1" ,
"PMERQ_29_1" ,
"PMERQ_33_1",
"PMERQ_35_1")

cols_cons_bf <- c("PMERQ_7_1" ,
"PMERQ_20_1" ,
"PMERQ_21_1" ,
"PMERQ_24_1",
"PMERQ_40_1",
"PMERQ_45_1")

cols_red_ip <- c("PMERQ_25_1" ,
"PMERQ_38_1" ,
"PMERQ_41_1")

cols_emo_share <- c("PMERQ_8_1" ,
"PMERQ_30_1" ,
"PMERQ_32_1")

cols_exp_sup <- c("PMERQ_1_1" ,
"PMERQ_16_1" ,
"PMERQ_34_1")

survey$PMERQ_conf_unpl_sit <- apply(PMERQ[cols_conf_unpl_sit], 1,sum)
survey$PMERQ_av_unpl_sit <- apply(PMERQ[cols_av_unpl_sit],1, sum)
survey$PMERQ_foc_ew <-apply(PMERQ[cols_foc_ew],1, sum)
survey$PMERQ_cog_dis <- apply(PMERQ[cols_cog_dis],1, sum)
survey$PMERQ_cons_bf<- apply(PMERQ[cols_cons_bf],1, sum)
survey$PMERQ_red_ip <- apply(PMERQ[cols_red_ip],1, sum)
survey$PMERQ_emo_share <- apply(PMERQ[cols_emo_share],1, sum)
survey$PMERQ_exp_sup <- apply(PMERQ[cols_exp_sup],1, sum)
survey$PMERQ_res_conf <- apply(PMERQ[cols_res_conf],1, sum)
survey$PMERQ_av_conf<- apply(PMERQ[cols_av_conf],1, sum)
```

#DERS
```{r}
DERS <- survey %>%
  dplyr::select("DERS_1_1":"DERS_41_1")

DERS <- as.data.frame(lapply(DERS[,], as.integer)) %>%
  drop_na()

cols_reverse <- c("DERS_24_1" ,
"DERS_28_1",
"DERS_7_1",
"DERS_3_1",
"DERS_12_1",
"DERS_21_1",
"DERS_9_1",
"DERS_39_1",
"DERS_26_1",
"DERS_8_1",
"DERS_1_1")

cols_non_ac <- c("DERS_29_1" ,
"DERS_25_1" ,
"DERS_15_1" ,
"DERS_14_1",
"DERS_33_1" ,
"DERS_27_1" )

cols_dif_gd <- c("DERS_30_1" ,
"DERS_22_1" ,
"DERS_16_1" ,
"DERS_38_1",
"DERS_24_1")

cols_imp_con <- c("DERS_37_1" ,
"DERS_31_1" ,
"DERS_17_1" ,
"DERS_23_1",
"DERS_4_1" ,
"DERS_28_1" )

cols_lack_ea <- c("DERS_7_1" ,
"DERS_3_1" ,
"DERS_12_1" ,
"DERS_21_1",
"DERS_9_1" ,
"DERS_39_1" )

cols_lim_ers <- c("DERS_20_1" ,
"DERS_19_1" ,
"DERS_25_1" ,
"DERS_40_1",
"DERS_32_1" ,
"DERS_26_1",
"DERS_41_1" ,
"DERS_34_1" )

cols_lack_ec <- c("DERS_6_1" ,
"DERS_5_1" ,
"DERS_10_1" ,
"DERS_8_1",
"DERS_1_1" )

DERS[cols_reverse] <- lapply(DERS[cols_reverse], reverseCode, min=1, max=5)

survey$DERS_non_ac <- apply(DERS[cols_non_ac], 1,sum)
survey$DERS_dif_gd <- apply(DERS[cols_dif_gd],1, sum)
survey$DERS_imp_con <-apply(DERS[cols_imp_con],1, sum)
survey$DERS_lack_ea <- apply(DERS[cols_lack_ea],1, sum)
survey$DERS_lim_ers<- apply(DERS[cols_lim_ers],1, sum)
survey$DERS_lack_ec <- apply(DERS[cols_lack_ec],1, sum)
```

#test
```{r}
gran_scores <- read.csv(file='../data/study3_granularityscores.csv')

survey_filtered <- survey  %>%
  subset(self.reportattention==1)

final <- merge(gran_scores, survey_filtered,by.x="ID",by.y="Participant.Public.ID.y")

cor.test(final$negmusicICC, final$negpicICC)
t.test(final$negmusicICC, final$negpicICC,paired=TRUE)
cor.test(final$posmusicICC, final$pospicICC)
t.test(final$posmusicICC, final$pospicICC,paired=TRUE)

ggplot(data=final,aes(x=negpicICC, y=negmusicICC)) +
  geom_point()+
  geom_smooth(method="lm")

ggplot(data=final,aes(x=pospicICC, y=posmusicICC)) +
  geom_point()+
  geom_smooth(method="lm")

hist(final$posmusicICC)
```

#associations
```{r}
#cor.test(final$negicICC, final$DERS_non_ac) still not working
cor.test(final$negpicICC, final$STAI_total)
cor.test(final$negmusicICC, final$STAI_total)

m1 <- lm(data=final,STAI_total ~ negpicICC + negmusicICC)
summary(m1)

# Fit model
m1 <- lm(data=final,STAI_total ~  negmusicICC)
# Compute studentized residuals
stud_res <- rstudent(m1)
# Identify potential outliers (> 3 in absolute value)
outliers <- which(abs(stud_res) > 3)
print(outliers)
# Visualize
plot(stud_res, ylab="Studentized Residuals", main="Outlier Detection")
abline(h = c(-3, 3), col = "red", lty = 2)

cor.test(final$negICC, final$STAI_S_total)
cor.test(final$negpicICC, final$STAI_S_total)
cor.test(final$negmusicICC, final$STAI_S_total)

m1 <- lm(data=final,STAI_S_total ~ negpicICC + negmusicICC)
summary(m1)

# Fit model
m1 <- lm(data=final,STAI_S_total ~  negmusicICC)
# Compute studentized residuals
stud_res <- rstudent(m1)
# Identify potential outliers (> 3 in absolute value)
outliers <- which(abs(stud_res) > 3)
print(outliers)
# Visualize
plot(stud_res, ylab="Studentized Residuals", main="Outlier Detection")
abline(h = c(-3, 3), col = "red", lty = 2)

cor.test(final$negICC, final$SCAARED_total)
cor.test(final$negpicICC, final$SCAARED_total)
cor.test(final$negmusicICC, final$SCAARED_total)

m1 <- lm(data=final,SCAARED_total ~ negpicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,SCAARED_total ~  negmusicICC)
# Compute studentized residuals
stud_res <- rstudent(m1)
# Identify potential outliers (> 3 in absolute value)
outliers <- which(abs(stud_res) > 3)
print(outliers)
# Visualize
plot(stud_res, ylab="Studentized Residuals", main="Outlier Detection")
abline(h = c(-3, 3), col = "red", lty = 2)

cor.test(final$negICC, final$BDI_total)
cor.test(final$negpicICC, final$BDI_total)
cor.test(final$negmusicICC, final$BDI_total)
cor.test(final$negICC, final$CD.RISC_total)
cor.test(final$negpicICC, final$CD.RISC_total)
cor.test(final$negmusicICC, final$CD.RISC_total)

m1 <- lm(data=final,BDI_total ~ negpicICC + negmusicICC)
summary(m1)

cor.test(final$posICC, final$CD.RISC_total)
cor.test(final$posmusicICC, final$CD.RISC_total)
cor.test(final$pospicICC, final$CD.RISC_total)

#########################

m1 <- lm(data=final,CD.RISC_total ~ pospicICC + posmusicICC)
summary(m1)

m1 <- lm(data=final,PMERQ_conf_unpl_sit ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,PMERQ_av_unpl_sit ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,PMERQ_foc_ew ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1) #here

m1 <- lm(data=final,PMERQ_cog_dis ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,PMERQ_cons_bf ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1) #here for images

m1 <- lm(data=final,PMERQ_red_ip ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,PMERQ_emo_share ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,PMERQ_exp_sup ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1) #here for images

m1 <- lm(data=final,PMERQ_res_conf ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,PMERQ_av_conf ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,DERS_non_ac ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,DERS_dif_gd ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1) #here for images

m1 <- lm(data=final,DERS_imp_con ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,DERS_lack_ea ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,DERS_lim_ers ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)

m1 <- lm(data=final,DERS_lack_ec ~ negpicICC + pospicICC + posmusicICC + negmusicICC)
summary(m1)
```


```{r}
library(corrplot)

survey_measures <- final %>%
  select(
    CD.RISC_total,
    STAI_total,
    STAI_S_total,
    BDI_total,
    SCAARED_total,
    PMERQ_conf_unpl_sit,
    PMERQ_av_unpl_sit,
    PMERQ_foc_ew,
    PMERQ_cog_dis,
    PMERQ_cons_bf,
    PMERQ_red_ip,
    PMERQ_emo_share,
    PMERQ_exp_sup,
    PMERQ_res_conf,
    PMERQ_av_conf,
    DERS_non_ac,
    DERS_dif_gd,
    DERS_imp_con,
    DERS_lack_ea,
    DERS_lim_ers,
    DERS_lack_ec,
    negmusicICC,
    posmusicICC,
    negpicICC,
    pospicICC,
    #commented back in 7/31/26
    negICC,
    posICC
  )

numeric_columns <- survey_measures[, sapply(survey_measures, is.numeric)]

# Calculate the correlation matrix
correlation_matrix<- cor(numeric_columns, use = "complete.obs")

# Compute p-values
p_values1 <- cor.mtest(numeric_columns)

p_values <- p_values1[["p"]]

# Specify the folder where you want to save the file
output_folder <- "../results/"

# Combine the folder path with the file name
output_file <- file.path(output_folder, "online_adul_corr.png")

# Open a PNG device with the specified file path
png(output_file, width = 800, height = 800)

# Generate the corrplot
corrplot(correlation_matrix, method = "circle", type = "upper", 
         p.mat = p_values, sig.level = 0.05, insig = "blank",
         tl.col = "black", tl.srt = 45, addCoef.col = NULL,
         col = colorRampPalette(c("blue", "white", "red"))(200))

# Close the PNG device
dev.off()

# Specify the folder where you want to save the file
output_folder <- "../results/structural/"

# Combine the folder path with the file name
output_file <- file.path(output_folder, "Structural Correlations Right Hemisphere 2-26-25.png")

# Open a PNG device with the specified file path
png(output_file, width = 800, height = 800)

# Generate the corrplot
corrplot(correlation_matrix_right, method = "circle", type = "upper", 
         p.mat = p_values_right, sig.level = 0.05, insig = "blank",
         tl.col = "black", tl.srt = 45, addCoef.col = NULL,
         col = colorRampPalette(c("blue", "white", "red"))(200))

title(main = "Structural Correlations Right Hemisphere Study 2", col.main = "black", font.main = 4)

# Close the PNG device
dev.off()

```

#all correlation plots
```{r}

##ALL POS CORR PLOTS
icc_vars <- c("posICC", "pospicICC", "posmusicICC")
survey_vars <- c("BDI_total", "STAI_S_total", "STAI_total", "CD.RISC_total", "SCAARED_total", "DERS_non_ac", "DERS_dif_gd", "DERS_imp_con", "DERS_lack_ea", "DERS_lim_ers", "DERS_lack_ec", "PMERQ_conf_unpl_sit", "PMERQ_av_unpl_sit", "PMERQ_foc_ew", "PMERQ_cog_dis", "PMERQ_cons_bf", "PMERQ_red_ip", "PMERQ_emo_share", "PMERQ_exp_sup", "PMERQ_res_conf", "PMERQ_av_conf")

results <- data.frame(
  icc = character(),
  survey = character(),
  r = numeric(),
  r_squared = numeric(),
  p_value = numeric(),
  n = integer(),
  stringsAsFactors = FALSE
)

for (icc in icc_vars) {
  for (survey in survey_vars) {
    
    complete_data <- final[!is.na(final[[icc]]) & !is.na(final[[survey]]), ]
    n_obs <- nrow(complete_data)
    
    r <- cor.test(complete_data[[icc]], complete_data[[survey]])
    r_val <- round(as.numeric(r$estimate), 3)
    r_squared <- round(as.numeric(r$estimate)^2, 3)
    p_val <- r$p.value
    
    # Print to console
    cat("\n---", icc, "vs", survey, "---\n")
    cat("r =", r_val, "\n")
    cat("R\u00b2 =", r_squared, "\n")
    cat("p =", round(p_val, 4), "\n")
    cat("n =", n_obs, "\n")
    
    results <- rbind(results, data.frame(
      icc = icc,
      survey = survey,
      r = r_val,
      r_squared = r_squared,
      p_value = round(p_val, 4),
      n = n_obs
    ))
    
    p_label <- if (p_val < 0.001) "< .001" else paste0("= ", round(p_val, 3))
    
    p <- ggplot(complete_data, aes(x = .data[[icc]], y = .data[[survey]])) +
      geom_point() +
      geom_smooth(method = "lm", se = TRUE, color = "blue") +
      labs(
        x = icc,
        y = survey,
        title = paste(icc, "vs", survey),
        subtitle = paste0("R\u00b2 = ", r_squared, "  |  p ", p_label, "  |  n = ", n_obs)
      ) +
      theme_minimal()
    
    ggsave(file.path("plots", paste0("plot_", icc, "_", survey, ".png")), 
           plot = p, width = 6, height = 5, dpi = 300)
    
    print(p)
  }
}

cat("\n=== Summary Table (sorted by strength of association) ===\n")
results <- results[order(-abs(results$r)), ]
rownames(results) <- NULL
print(results)

##ALL NEG CORR PLOTS

library(ggplot2)

icc_vars <- c("negICC", "negpicICC", "negmusicICC")
survey_vars <- c("BDI_total", "STAI_S_total", "STAI_total", "CD.RISC_total", "SCAARED_total", "DERS_non_ac", "DERS_dif_gd", "DERS_imp_con", "DERS_lack_ea", "DERS_lim_ers", "DERS_lack_ec", "PMERQ_conf_unpl_sit", "PMERQ_av_unpl_sit", "PMERQ_foc_ew", "PMERQ_cog_dis", "PMERQ_cons_bf", "PMERQ_red_ip", "PMERQ_emo_share", "PMERQ_exp_sup", "PMERQ_res_conf", "PMERQ_av_conf")

results <- data.frame(
  icc = character(),
  survey = character(),
  r = numeric(),
  r_squared = numeric(),
  p_value = numeric(),
  n = integer(),
  stringsAsFactors = FALSE
)

for (icc in icc_vars) {
  for (survey in survey_vars) {
    
    complete_data <- final[!is.na(final[[icc]]) & !is.na(final[[survey]]), ]
    n_obs <- nrow(complete_data)
    
    r <- cor.test(complete_data[[icc]], complete_data[[survey]])
    r_val <- round(as.numeric(r$estimate), 3)
    r_squared <- round(as.numeric(r$estimate)^2, 3)
    p_val <- r$p.value
    
    # Print to console
    cat("\n---", icc, "vs", survey, "---\n")
    cat("r =", r_val, "\n")
    cat("R\u00b2 =", r_squared, "\n")
    cat("p =", round(p_val, 4), "\n")
    cat("n =", n_obs, "\n")
    
    results <- rbind(results, data.frame(
      icc = icc,
      survey = survey,
      r = r_val,
      r_squared = r_squared,
      p_value = round(p_val, 4),
      n = n_obs
    ))
    
    p_label <- if (p_val < 0.001) "< .001" else paste0("= ", round(p_val, 3))
    
    p <- ggplot(complete_data, aes(x = .data[[icc]], y = .data[[survey]])) +
      geom_point() +
      geom_smooth(method = "lm", se = TRUE, color = "blue") +
      labs(
        x = icc,
        y = survey,
        title = paste(icc, "vs", survey),
        subtitle = paste0("R\u00b2 = ", r_squared, "  |  p ", p_label, "  |  n = ", n_obs)
      ) +
      theme_minimal()
    
    ggsave(file.path("plots", paste0("plot_", icc, "_", survey, ".png")), 
           plot = p, width = 6, height = 5, dpi = 300)
    
    print(p)
  }
}

cat("\n=== Summary Table (sorted by strength of association) ===\n")
results <- results[order(-abs(results$r)), ]
rownames(results) <- NULL
print(results)


#PLOT FOR SLIDE 28 replication 8/5/26
library(ggplot2)

x_var <- "posmusicICC"
y_var <- "pospicICC"

# Remove missing data for this pair
plot_data <- final[!is.na(final[[x_var]]) & !is.na(final[[y_var]]), ]

# Calculate correlation
r <- cor.test(plot_data[[x_var]], plot_data[[y_var]])
r_val <- round(as.numeric(r$estimate), 2)

# Build plot
p <- ggplot(plot_data, aes(x = .data[[x_var]], y = .data[[y_var]])) +
  geom_point(color = "black", size = 2, alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE, color = "steelblue", fill = "lightblue") +
  annotate(
    "text",
    x = max(plot_data[[x_var]], na.rm = TRUE),
    y = min(plot_data[[y_var]], na.rm = TRUE),
    label = paste0("r = ", r_val),
    hjust = 1, vjust = 0,
    size = 5
  ) +
  labs(
    x = "Positive Emotion Granularity Score - Music",
    y = "Positive Emotion Granularity Score - Pictures"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    panel.grid.minor = element_blank(),
    axis.title = element_text(face = "bold")
  )

print(p)

#NEG VERSION of above
x_var <- "negmusicICC"
y_var <- "negpicICC"

# Remove missing data for this pair
plot_data <- final[!is.na(final[[x_var]]) & !is.na(final[[y_var]]), ]

# Calculate correlation
r <- cor.test(plot_data[[x_var]], plot_data[[y_var]])
r_val <- round(as.numeric(r$estimate), 2)

# Build plot
p <- ggplot(plot_data, aes(x = .data[[x_var]], y = .data[[y_var]])) +
  geom_point(color = "black", size = 2, alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE, color = "steelblue", fill = "lightblue") +
  annotate(
    "text",
    x = max(plot_data[[x_var]], na.rm = TRUE),
    y = min(plot_data[[y_var]], na.rm = TRUE),
    label = paste0("r = ", r_val),
    hjust = 1, vjust = 0,
    size = 5
  ) +
  labs(
    x = "Negative Emotion Granularity Score - Music",
    y = "Negative Emotion Granularity Score - Pictures"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    panel.grid.minor = element_blank(),
    axis.title = element_text(face = "bold")
  )

print(p)

```
#HEATMAP of ICCs vs. Surveys
```{r}
library(ggplot2)
library(reshape2)

icc_vars <- c("negICC", "negpicICC", "negmusicICC", "posICC", "pospicICC", "posmusicICC")
survey_vars <- c("BDI_total", "STAI_S_total", "STAI_T_total", "CD.RISC_total", "SCAARED_total")

# Build a correlation matrix (rows = ICC vars, cols = survey vars)
cor_matrix <- matrix(NA, nrow = length(icc_vars), ncol = length(survey_vars),
                      dimnames = list(icc_vars, survey_vars))
p_matrix <- cor_matrix  # store p-values too, for optional significance marking

for (icc in icc_vars) {
  for (survey in survey_vars) {
    complete_data <- final[!is.na(final[[icc]]) & !is.na(final[[survey]]), ]
    test <- cor.test(complete_data[[icc]], complete_data[[survey]])
    cor_matrix[icc, survey] <- test$estimate
    p_matrix[icc, survey] <- test$p.value
  }
}

# Reshape into long format for ggplot
cor_long <- melt(cor_matrix, varnames = c("icc", "survey"), value.name = "r")
p_long <- melt(p_matrix, varnames = c("icc", "survey"), value.name = "p")
heat_data <- merge(cor_long, p_long, by = c("icc", "survey"))

# Add significance stars
heat_data$sig <- ifelse(heat_data$p < 0.001, "***",
                  ifelse(heat_data$p < 0.01, "**",
                  ifelse(heat_data$p < 0.05, "*", "")))

# Build heatmap
p <- ggplot(heat_data, aes(x = survey, y = icc, fill = r)) +
  geom_tile(color = "white") +
  geom_text(aes(label = paste0(round(r, 2), sig)), size = 4) +
  scale_fill_gradient2(
    low = "steelblue", mid = "white", high = "firebrick",
    midpoint = 0, limits = c(-1, 1), name = "r"
  ) +
  labs(
    x = "Survey Measure",
    y = "ICC Variable",
    title = "Correlation Heatmap: ICC Variables vs Survey Measures",
    caption = "* p < .05   ** p < .01   *** p < .001"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )

print(p)

ggsave("ICCSurvey_correlation_heatmap.png", plot = p, width = 8, height = 6, dpi = 300)

```


