---
title: "Dev_Stress_Task"
output: html_document
date: "2024-02-05"
---

```{r setup, include=FALSE}
library(tidyverse)
library(irr)
```

```{r}
data <- read.csv("../data/pilot data/Dev Stress Task Norming_February 12, 2024_13.43 - Dev Stress Task Norming_February 5, 2024_13.43.csv") # %>%
  # select("Q2","X54_anger_1":"self.reportattention")

granularity_data <- data %>%
  select("X54_anger_1":"pos3_satisfied_1")

granularity_pic <- granularity_data %>%
  select("X54_anger_1":"X1710_satisfied_1")

granularity_music <- granularity_data %>%
  select("pos2_anger_1":"pos3_satisfied_1")

granularity_pic_negative <- granularity_pic %>%
  select(ends_with("anger_1") | ends_with("disgust_1") | ends_with("sadness_1") | ends_with("scared_1") | ends_with("upset_1"))

granularity_pic_positive <- granularity_pic %>%
  select(ends_with("happiness_1") | ends_with("pride_1") | ends_with("excitement_1") | ends_with("joy_1") | ends_with("satisfied_1"))

granularity_music_negative <- granularity_music %>%
  select(ends_with("anger_1") | ends_with("disgust_1") | ends_with("sadness_1") | ends_with("scared_1") | ends_with("upset_1") )

granularity_music_positive <- granularity_music %>%
  select(ends_with("happiness_1") | ends_with("pride_1") | ends_with("excitement_1") | ends_with("joy_1") | ends_with("satisfied_1"))

##NICK 2/20 edits. this will be code to use for negative emotions in response to both music + pics
  anger <-
    data %>%
    select(ends_with("anger_1") | Q2) %>% 
    pivot_longer(!Q2, values_to="anger") %>%
    select(-c( "name"))
  
  disgust <-
    data %>%
    select(ends_with("disgust_1") | Q2) %>% 
    pivot_longer(!Q2,values_to="disgust") %>%
    select(-c("Q2","name"))
  
  sadness <-
    data %>%
    select(ends_with("sadness_1") | Q2) %>% 
    pivot_longer(!Q2,values_to = "sadness") %>%
    select(-c("Q2","name"))

  scared <-
    data %>%
    select(ends_with("scared_1") | Q2) %>% 
    pivot_longer(!Q2, values_to="scared") %>%
    select(-c("Q2","name"))

  upset <-
    data %>%
    select(ends_with("upset_1") | Q2) %>% 
    pivot_longer(!Q2, values_to="upset") %>%
    select(-c("Q2","name"))

master_negative <- cbind(anger, disgust, sadness,scared,upset)

#to get a single score:
master_negative %>%
  subset(Q2=="62fc6762d2d8e46c4e75b469") %>% 
  select(-c("Q2")) %>%
  icc(type = "agreement", unit = "single")

i = 1
master_negative$ICC <- NA
while (i <= nrow(master_negative)) {
  subset_data <- master_negative[i:min(i + 11, nrow(master_negative)), ]
  subset_data <- subset_data[, !names(subset_data) %in% c("Q2", "ICC")]
  result <- icc(subset_data, type = "agreement", unit = "single")
  print(result$value)
  i <- i + 12
}

  happiness <-
    data %>%
    select(ends_with("happiness_1") | Q2) %>% 
    pivot_longer(!Q2, values_to="happiness") %>%
    select(-c( "name"))
  
  pride <-
    data %>%
    select(ends_with("pride_1") | Q2) %>% 
    pivot_longer(!Q2,values_to="pride") %>%
    select(-c("Q2","name"))
  
  excitement <-
    data %>%
    select(ends_with("excitement_1") | Q2) %>% 
    pivot_longer(!Q2,values_to = "excitement") %>%
    select(-c("Q2","name"))

  joy <-
    data %>%
    select(ends_with("joy_1") | Q2) %>% 
    pivot_longer(!Q2, values_to="joy") %>%
    select(-c("Q2","name"))

  satisfied <-
    data %>%
    select(ends_with("satisfied_1") | Q2) %>% 
    pivot_longer(!Q2, values_to="satisfied") %>%
    select(-c("Q2","name"))

master_positive <- cbind(happiness, pride, excitement, joy, satisfied)

i = 1
master_positive$ICC <- NA
while (i <= nrow(master_positive)) {
  subset_data <- master_positive[i:min(i + 11, nrow(master_positive)), ]
  subset_data <- subset_data[, !names(subset_data) %in% c("Q2", "ICC")]
  result <- icc(subset_data, type = "agreement", unit = "single")
  print(result$value)
  i <- i + 12
}
```


```{r}
# install.packages("irr")
library(irr)
# calculate ICC for each positive or negative term

# granularity_music_negative <- granularity_music_negative[-1, ]

calculate_icc_and_add <- function(row_data, df) {
  # Check if the row contains at least 2 values
  if(length(row_data) < 2) {
    stop("At least 2 values are required to calculate ICC.")
  }
  
  # Create a dummy dataframe with two columns: Subject and Measurement
  dummy_df <- data.frame(Subject = 1:length(row_data), Measurement = row_data)
  
  # Calculate ICC using irr package
  icc_result <- icc(dummy_df, model = "oneway", type = "agreement", unit = "single")
  
  # Extract ICC value
  icc_value <- icc_result$value
  
  # Add ICC value to dataframe
  df$ICC <- icc_value
  
  return(dummy_df)
}

i <- 1:length(granularity_music_negative)
for (i in nrow(granularity_music_negative)) {
  df_with_icc <- calculate_icc_and_add(granularity_music_negative[i,], granularity_music_negative)
}
df_with_icc <- calculate_icc_and_add(granularity_music_negative[4,], granularity_music_negative)

granularity_music_negative$ICC <- NA
i = 2
# in nrow(granularity_music_negative)) {
# for (i  {
dummy_df <- data.frame(Measurement = granularity_music_negative[i,])
dummy_DF <- as.data.frame(t(dummy_df))
icc(dummy_DF)
icc_value <- icc(dummy_df)
granularity_music_negative$ICC[i] <- icc_value 
# }


dummy_df$ICC <- icc(dummy_df)
granularity_music_negative %>%
  drop_na() %>%
    icc()
```
