---
title: "redcap_scoring"
output: html_document
date: "2024-08-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 library(tidyverse)
source("reverseCode.R")

df <- read.csv("../data/redcap/TEAMYAInPersonSurvey_DATA_2024-08-15_0040.csv")
```

#skip for now, missing a Q
```{r}
Gold <- df %>%
  dplyr::select(goldmsi_1_v2:goldmsi_38_v2)
  
 # dplyr::select("X1..I.spend.a.lot.of.my.free.time.doing.music.related.activities....Completely.Disagree.Completely.Agree":"X38..I.listen.attentively.to.music.for.___.per.day.")

#delete atttention checking question
Gold$goldmsi_38_v2 <- NULL

Gold <- as.data.frame(lapply(Gold[,], as.integer))

# GoldMSI columns to reverse code and sub-score (for these questions, the correct answer (ie the more positive answer) is a higher number. Negative questions are reverse coded.) 

cols_reverse <- c("goldmsi_21_v2" ,
"goldmsi_11_v2" ,
"goldmsi_13_v2" ,
"goldmsi_23_v2" ,
"goldmsi_14_v2" ,
"goldmsi_27_v2" ,
"goldmsi_17_v2" ,
"goldmsi_25_v2" ,
"goldmsi_9_v2")

cols_activeengagement <- c("goldmsi_1_v2" ,
"goldmsi_3_v2" ,
"goldmsi_8_v2" ,
"goldmsi_15_v2" ,
"goldmsi_21_v2" ,
"goldmsi_24_v2" ,
"goldmsi_28_v2" ,
"goldmsi_34_v2" ,
"goldmsi_38_v2")

cols_perceptualabilities <- c("goldmsi_5_v2" ,
"goldmsi_6_v2" ,
"goldmsi_11_v2" ,
"goldmsi_12_v2" ,
"goldmsi_13_v2" ,
"goldmsi_18_v2" ,
"goldmsi_22_v2" ,
"goldmsi_23_v2" ,
"goldmsi_26_v2")

cols_musicaltraining <- c("goldmsi_14_v2" , "goldmsi_27_v2",
"goldmsi_32_v2" ,
"goldmsi_33_v2" , ## think about how this is scored? doesn't seem like a lot of people answered
"goldmsi_35_v2" ,
"goldmsi_36_v2" ,
"goldmsi_37_v2")


cols_singingabilities <- c("goldmsi_4_v2" ,
"goldmsi_7_v2" ,
"goldmsi_10_v2" ,
"goldmsi_17_v2" ,
"goldmsi_25_v2" ,
"goldmsi_29_v2" ,
"goldmsi_30_v2")

cols_emotion <- c("goldmsi_2_v2" ,
"goldmsi_9_v2" ,
"goldmsi_16_v2" ,
"goldmsi_19_v2" ,
"goldmsi_20_v2" ,
"goldmsi_31_v2")

cols_musicalsophistication <- c("goldmsi_1_1" ,
           "goldmsi_3_1" ,
"goldmsi_4_1" ,
"goldmsi_7_1" ,
"goldmsi_10_1" ,
"goldmsi_12_1" ,
"goldmsi_14_1" ,
"goldmsi_15_1" ,
"goldmsi_17_1" ,
"goldmsi_19_1" ,
"goldmsi_23_1" ,
"goldmsi_24_1" ,
"goldmsi_25_1" ,
"goldmsi_27_1" ,
"goldmsi_29_1" ,
"goldmsi_32" ,
"goldmsi_33")

# Reverse code

Gold[cols_reverse] <- lapply(Gold[cols_reverse], reverseCode, min=1, max=7)

# Add sub-scores and total to main df

df$Gold_total <- apply(Gold,1, sum)/38 # total GoldMSI score
df$Gold_activeengagement <- apply(Gold[cols_activeengagement], 1,sum)/9
df$Gold_perceptualabilities <- apply(Gold[cols_perceptualabilities],1, sum)/9
df$Gold_musicaltraining <-apply(Gold[cols_musicaltraining],1, sum)/7
df$Gold_singingabilities <- apply(Gold[cols_singingabilities],1, sum)/7
df$Gold_emotion <- apply(Gold[cols_emotion],1, sum)/6
df$Gold_musicalsophistication <- apply(Gold[cols_musicalsophistication],1, sum)/18

hist(df$Gold_total)
```
#eBMRQ
```{r}
bmrq <- df %>%
  dplyr::select("ebmrq_1":"ebmrq_20", "aims_3","aims_13", "aims_15", "aims_29")

bmrq <- as.data.frame(lapply(bmrq[,], as.integer))

# BMRQ columns to reverse code and sub-score
cols_reverse <- c("ebmrq_2",
                  "ebmrq_5")

cols_emotion <- c("ebmrq_3",
  "ebmrq_8",
  "ebmrq_12",
  "ebmrq_18")

cols_sensorimotor <-c("ebmrq_5",
  "ebmrq_10",
  "ebmrq_15",
  "ebmrq_20")
                      
cols_moodreg <- c("ebmrq_4",
  "ebmrq_9",
  "ebmrq_14",
  "ebmrq_19")

cols_musicseek <- c("ebmrq_2",
  "ebmrq_7",
  "ebmrq_11",
  "ebmrq_17")

cols_socialreward <-c("ebmrq_1",
  "ebmrq_6",
  "ebmrq_13",
  "ebmrq_16")

cols_absorption <- c("aims_3","aims_13", "aims_15", "aims_29")

# Reverse code
bmrq[cols_reverse] <- lapply(bmrq[cols_reverse], reverseCode)

# Add sub-scores and total to main df
df$eBMRQ_total <- apply(bmrq,1, sum) 
df$BMRQ_emotion <- apply(bmrq[cols_emotion], 1,sum)
df$BMRQ_sensorimotor <- apply(bmrq[cols_sensorimotor],1, sum)
df$BMRQ_moodreg <-apply(bmrq[cols_moodreg],1, sum)
df$BMRQ_musicseek <- apply(bmrq[cols_musicseek],1, sum)
df$BMRQ_socialreward <- apply(bmrq[cols_socialreward],1, sum)
df$BMRQ_absorption<- apply(bmrq[cols_absorption],1, sum)

hist(df$eBMRQ_total)
```

#M@H
```{r}
MH <- df %>%
  dplyr::select("mhr_1":"mhr_20")

#MH <- MH[complete.cases(MH),]
MH <- as.data.frame(lapply(MH[,], as.integer))

cols_reverse <- c("mhr_6","mhr_7","mhr_11","mhr_12","mhr_18","mhr_19","mhr_20")
MH[cols_reverse] <- lapply(MH[cols_reverse], reverseCode, min=1, max=7)

df$MH_total <- apply(MH,1, sum) # total M@H scores
hist(df$MH_total)

# # started putting these together but I'm not sure what goes where
# cols_caregiverbeliefs <- c("M.H_child1_1", "M.H_child2_1", "M.H_child3_1", "M.H_child4_1")
# 
# cols_caregiversinging <- c("M.H_child9_1")
# 
# cols_childhoodattitude <- c("M.H_child8_1")
# 
# cols_socialcontexts <- c("")
# 
# cols_musicmaking <- c("M.H_child5_1", "M.H_child6_1", "M.H_child7_1")
# 
# df$MH_caregiverbeliefs <- apply(MH[cols_caregiverbeliefs], 1,sum)
# df$MH_caregiversinging <- apply(MH[cols_caregiversinging],1, sum)
# df$MH_childhoodattitude <-apply(MH[cols_childhoodattitude],1, sum)
# df$MH_socialcontexts <- apply(MH[cols_socialcontexts],1, sum)
# df$MH_musicmaking <- apply(MH[cols_musicmaking],1, sum)
```

#RDEES
```{r}
rdees <- df %>%
  dplyr::select("rdees_1":"rdees_14")

cols_reverse <- c("rdees_1","rdees_5","rdees_9", "rdees_11")

rdees <- as.data.frame(lapply(rdees[,], as.integer))

rdees[cols_reverse] <- lapply(rdees[cols_reverse], reverseCode, min=1, max=5)

cols_range <- c("rdees_1","rdees_3","rdees_5","rdees_7", "rdees_9", "rdees_11", "rdees_13")
cols_differentation <- c("rdees_2","rdees_4","rdees_6","rdees_8", "rdees_10", "rdees_12", "rdees_14")

df$rdees_range <- apply(rdees[cols_range], 1,sum)
df$rdees_differentiation <- apply(rdees[cols_differentation],1, sum)
df$rdees_total <- df$rdees_differentiation + df$rdees_range

hist(df$rdees_total)

redcap_scores <- 
  df %>%
  subset(participant_id=="TEAM_YA_032" | participant_id=="TEAM_YA_033" | participant_id=="TEAM_YA_035") %>%
  select(participant_id, eBMRQ_total:rdees_total)

write.csv(redcap_scores,'../data/redcap/redcap_scores.csv')
```