---
title: "adult_onlinecleaning"
output: html_document
date: "2025-12-20"
---

```{r}
library(lmerTest)
library(tidyverse)
library(psych)
library(irr)
source("reverseCode.R")
```

#---------Load in data--------
```{r}
data_1 <- read.csv("../data/adult_online_study2/data_exp_169297-v29/data_exp_169297-v29_task-6dig.csv") 

data_2 <- read.csv("../data/adult_online_study2/data_exp_169297-v30/data_exp_169297-v30_task-6dig.csv") 

granularity_data <- bind_rows(data_1, data_2)

#survey scoring
#demo <- read.csv("~/Desktop/prolific_demographic_export_694574e84a79b38d198a03cb (3).csv") %>%
#  subset(Status == "APPROVED")

survey <- read.csv('../data/adult_online_study2/emo_granularity_adultonline_December 29, 2025_16.35.csv')

IDs <- read.csv('../data/adult_online_study2/qual_task_link.csv')
IDs <- IDs[rowSums(IDs == "" | is.na(IDs)) != ncol(IDs), ]

survey <- merge(survey,IDs,by="ResponseId",all.y = TRUE)
```

```{r}
## Separating by picture vs music, removing practice stims
granularity_pic <- granularity_data %>%
  filter(Spreadsheet..Image != "") %>%
  filter(Spreadsheet..Image != "Coffee 1.jpg") %>%
  select(-c("Spreadsheet..Audio"))%>%
  #select(Participant.Public.ID, Response) %>%
  mutate(Response = as.numeric(Response)) %>%
  subset(Response !="") 

granularity_music <- granularity_data %>%
  filter(Spreadsheet..Audio != "") %>%
  filter(Spreadsheet..Audio != "8_pieceA_dreamy_calm_joyous_1.mp3") %>%
  select(-c("Spreadsheet..Image")) %>%
  #select(Participant.Public.ID, Response) %>%
  subset(Response !="" & Response !="audio started" & Response !="audio finished" ) %>%
  mutate(Response = as.numeric(Response)) %>%
  distinct(Participant.Public.ID, Spreadsheet..Audio,Object.Name,.keep_all = TRUE)
```


##-----Subsetting by valence and stimulus type--------
```{r}
# List of emotions
emotions <- list(
  neg = c("Gloomy", "Sad", "Scared", "Anxious", "Upset"),
  pos = c("Happy", "Satisfied", "Excited", "Joyful", "Relaxed")
)

# Function to filter and rename
filter_and_rename <- function(data, emotion, media_type, keep_id = FALSE) {
  columns_to_select <- if (keep_id) {
    c("Participant.Public.ID", "Response")
  } else {
    c("Response")
  }
  
  data %>%
    filter(Object.Name == paste(emotion, "Slider")) %>%
    select(-c(paste0("Spreadsheet..", media_type), "Object.Name")) %>%
    select(all_of(columns_to_select)) %>%
    rename(!!tolower(emotion) := "Response")
}

# General function to apply filtering to both media types and emotion types
apply_filter <- function(data, emotions, media_type) {
  lapply(seq_along(emotions), function(i) {
    filter_and_rename(data, emotions[i], media_type, keep_id = (i == 1))
  }) %>% bind_cols() %>% na.omit()
}

# Apply the process for each combination of data and emotion types
music_negative <- apply_filter(granularity_music, emotions$neg, "Audio")
music_positive <- apply_filter(granularity_music, emotions$pos, "Audio")
pic_negative <- apply_filter(granularity_pic, emotions$neg, "Image")
pic_positive <- apply_filter(granularity_pic, emotions$pos, "Image")

negative <- rbind(music_negative, pic_negative)
positive <- rbind(music_positive, pic_positive)
```

##----Scoring ICC------
```{r}
# ICC with Fisher transformation and recoding of negative correlations
compute_icc_fisher_recode <- function(data_list) {
  sapply(data_list, function(data) {
    icc_result <- data %>%
      select(-Participant.Public.ID) %>%
      icc(model = "twoway", type = "consistency", unit = "average")
    
    # Recode correlations less than 0 as 0
    icc_value <- ifelse(icc_result$value < 0, 0, icc_result$value)
    
    # Fisher transformation and reverse scoring
    -1 * fisherz(icc_value)
  })
}

# Create lists of data frames split by Participant.Public.ID
music_negative_list <- split(music_negative, music_negative$Participant.Public.ID)
music_positive_list <- split(music_positive, music_positive$Participant.Public.ID)
pic_negative_list <- split(pic_negative, pic_negative$Participant.Public.ID)
pic_positive_list <- split(pic_positive, pic_positive$Participant.Public.ID)

positive_list <- split(positive, positive$Participant.Public.ID)
negative_list <- split(negative, negative$Participant.Public.ID)

###
results_recode <- data.frame(ID = names(music_negative_list))
results_recode$negmusicICC <- compute_icc_fisher_recode(music_negative_list)
results_recode$posmusicICC <- compute_icc_fisher_recode(music_positive_list)
results_recode$negpicICC <- compute_icc_fisher_recode(pic_negative_list)
results_recode$pospicICC <- compute_icc_fisher_recode(pic_positive_list)
results_recode$negICC <- compute_icc_fisher_recode(negative_list)
results_recode$posICC <- compute_icc_fisher_recode(positive_list)
results_recode$allmusicICC <- rowMeans(results_recode[, c("negmusicICC", "posmusicICC")], na.rm = TRUE)
results_recode$allpicICC <- rowMeans(results_recode[, c("negpicICC", "pospicICC")], na.rm = TRUE)
```

#adding labels for stims to rating df
```{r}
granularity_music_labels <- 
  granularity_music %>%
  distinct(Participant.Public.ID,Spreadsheet..Audio)

granularity_pic_labels <- 
  granularity_pic %>%
  distinct(Participant.Public.ID,Spreadsheet..Image)


music_negative <- cbind(music_negative,granularity_music_labels[2])
names(music_negative)[7] <- "stim"
music_negative$condition <- "music"
music_positive <- cbind(music_positive,granularity_music_labels[2])
music_positive$condition <- "music"
names(music_positive)[7] <- "stim"

pic_negative <- cbind(pic_negative,granularity_pic_labels[2])
names(pic_negative)[7] <- "stim"
pic_negative$condition <- "pic"
pic_positive <- cbind(pic_positive,granularity_pic_labels[2])
names(pic_positive)[7] <- "stim"
pic_positive$condition <- "pic"

negative_ratings <- rbind(pic_negative,music_negative)
positive_ratings <- rbind(pic_positive,music_positive)
```


#CDRISC
```{r}
CD.RISC <- survey %>%
  dplyr::select("CD.RISC1_1":"CD.RISC10_1")

CD.RISC <- as.data.frame(lapply(CD.RISC[,], as.integer)) %>%
  drop_na()

survey$CD.RISC_total <- apply(CD.RISC,1,sum)
hist(survey$CD.RISC_total)
```

#STAI-T
```{r}
STAI_T <- survey %>%
  dplyr::select("STAI1_1":"STAI20_1")

STAI_T <- as.data.frame(lapply(STAI_T[,], as.integer)) %>%
  drop_na()

cols_reverse <- c("STAI1_1","STAI3_1","STAI6_1","STAI7_1","STAI10_1","STAI13_1","STAI14_1","STAI16_1","STAI19_1")
STAI_T[cols_reverse] <- lapply(STAI_T[cols_reverse], reverseCode, min=1, max=4)

survey$STAI_total <- apply(STAI_T,1,sum)
```

#STAI-S
```{r}
STAI_S <- survey %>%
  dplyr::select("STAI.S_1_1":"STAI.S_20_1")

STAI_S <- as.data.frame(lapply(STAI_S[,], as.integer)) %>%
  drop_na()

cols_reverse <- c("STAI.S_1_1","STAI.S_2_1","STAI.S_5_1","STAI.S_8_1","STAI.S_10_1","STAI.S_11_1","STAI.S_15_1","STAI.S_16_1","STAI.S_19_1","STAI.S_20_1")
STAI_S[cols_reverse] <- lapply(STAI_S[cols_reverse], reverseCode, min=1, max=4)

survey$STAI_S_total <- apply(STAI_S,1,sum)
```

#BDI
```{r}
BDI <- survey %>%
  dplyr::select("BDI_1":"BDI_20")

BDI$BDI_15[BDI$BDI_15 == 3] <- 2
BDI$BDI_15[BDI$BDI_15 == 4 | BDI$BDI_15 == 5] <- 3
BDI$BDI_15[BDI$BDI_15 == 6 | BDI$BDI_15 == 7] <- 4

BDI$BDI_17[BDI$BDI_17 == 3] <- 2
BDI$BDI_17[BDI$BDI_17 == 4 | BDI$BDI_17 == 5] <- 3
BDI$BDI_17[BDI$BDI_17 == 6 | BDI$BDI_17 == 7] <- 4

BDI[BDI == 1] <- 0
BDI[BDI == 2] <- 1
BDI[BDI == 3] <- 2
BDI[BDI == 4] <- 3

BDI <- as.data.frame(lapply(BDI[,], as.integer))

survey$BDI_total <- apply(BDI,1,sum)
hist(survey$BDI_total)
```

#SCAARED
```{r}
scaared <- survey %>%
  dplyr::select("SCAARED1_1":"SCAARED44_1") 

scaared <- as.data.frame(lapply(scaared[,], as.integer)) %>%
  drop_na() #get subscales

survey$SCAARED_total <- apply(scaared,1,sum)
```

#PMERQ
```{r}
PMERQ <- survey %>%
  dplyr::select("PMERQ_1_1":"PMERQ_45_1")

PMERQ <- as.data.frame(lapply(PMERQ[,], as.integer)) %>%
  drop_na()

cols_conf_unpl_sit <- c("PMERQ_9_1" ,
"PMERQ_11_1" ,
"PMERQ_15_1" ,
"PMERQ_28_1")

cols_av_unpl_sit <- c("PMERQ_4_1" ,
"PMERQ_5_1" ,
"PMERQ_12_1" ,
"PMERQ_18_1",
"PMERQ_42_1" ,
"PMERQ_44_1" )

cols_res_conf <- c("PMERQ_6_1" ,
"PMERQ_17_1" ,
"PMERQ_19_1" ,
"PMERQ_26_1",
"PMERQ_36_1" ,
"PMERQ_39_1" )

cols_av_conf <- c("PMERQ_3_1" ,
"PMERQ_10_1" ,
"PMERQ_14_1" ,
"PMERQ_37_1",
"PMERQ_43_1")

cols_foc_ew <- c("PMERQ_2_1" ,
"PMERQ_22_1" ,
"PMERQ_23_1" ,
"PMERQ_31_1")

cols_cog_dis <- c("PMERQ_13_1" ,
"PMERQ_27_1" ,
"PMERQ_29_1" ,
"PMERQ_33_1",
"PMERQ_35_1")

cols_cons_bf <- c("PMERQ_7_1" ,
"PMERQ_20_1" ,
"PMERQ_21_1" ,
"PMERQ_24_1",
"PMERQ_40_1",
"PMERQ_45_1")

cols_red_ip <- c("PMERQ_25_1" ,
"PMERQ_38_1" ,
"PMERQ_41_1")

cols_emo_share <- c("PMERQ_8_1" ,
"PMERQ_30_1" ,
"PMERQ_32_1")

cols_exp_sup <- c("PMERQ_1_1" ,
"PMERQ_16_1" ,
"PMERQ_34_1")

survey$PMERQ_conf_unpl_sit <- apply(PMERQ[cols_conf_unpl_sit], 1,sum)
survey$PMERQ_av_unpl_sit <- apply(PMERQ[cols_av_unpl_sit],1, sum)
survey$PMERQ_foc_ew <-apply(PMERQ[cols_foc_ew],1, sum)
survey$PMERQ_cog_dis <- apply(PMERQ[cols_cog_dis],1, sum)
survey$PMERQ_cons_bf<- apply(PMERQ[cols_cons_bf],1, sum)
survey$PMERQ_red_ip <- apply(PMERQ[cols_red_ip],1, sum)
survey$PMERQ_emo_share <- apply(PMERQ[cols_emo_share],1, sum)
survey$PMERQ_exp_sup <- apply(PMERQ[cols_exp_sup],1, sum)
survey$PMERQ_res_conf <- apply(PMERQ[cols_res_conf],1, sum)
survey$PMERQ_av_conf<- apply(PMERQ[cols_av_conf],1, sum)
```

#DERS
```{r}
DERS <- survey %>%
  dplyr::select("DERS_1_1":"DERS_41_1")

DERS <- as.data.frame(lapply(DERS[,], as.integer)) %>%
  drop_na()

cols_reverse <- c("DERS_24_1" ,
"DERS_28_1",
"DERS_7_1",
"DERS_3_1",
"DERS_12_1",
"DERS_21_1",
"DERS_9_1",
"DERS_39_1",
"DERS_26_1",
"DERS_8_1",
"DERS_1_1")

cols_non_ac <- c("DERS_29_1" ,
"DERS_25_1" ,
"DERS_15_1" ,
"DERS_14_1",
"DERS_33_1" ,
"DERS_27_1" )

cols_dif_gd <- c("DERS_30_1" ,
"DERS_22_1" ,
"DERS_16_1" ,
"DERS_38_1",
"DERS_24_1")

cols_imp_con <- c("DERS_37_1" ,
"DERS_31_1" ,
"DERS_17_1" ,
"DERS_23_1",
"DERS_4_1" ,
"DERS_28_1" )

cols_lack_ea <- c("DERS_7_1" ,
"DERS_3_1" ,
"DERS_12_1" ,
"DERS_21_1",
"DERS_9_1" ,
"DERS_39_1" )

cols_lim_ers <- c("DERS_20_1" ,
"DERS_19_1" ,
"DERS_25_1" ,
"DERS_40_1",
"DERS_32_1" ,
"DERS_26_1",
"DERS_41_1" ,
"DERS_34_1" )

cols_lack_ec <- c("DERS_6_1" ,
"DERS_5_1" ,
"DERS_10_1" ,
"DERS_8_1",
"DERS_1_1" )

DERS[cols_reverse] <- lapply(DERS[cols_reverse], reverseCode, min=1, max=5)

survey$DERS_non_ac <- apply(DERS[cols_non_ac], 1,sum)
survey$DERS_dif_gd <- apply(DERS[cols_dif_gd],1, sum)
survey$DERS_imp_con <-apply(DERS[cols_imp_con],1, sum)
survey$DERS_lack_ea <- apply(DERS[cols_lack_ea],1, sum)
survey$DERS_lim_ers<- apply(DERS[cols_lim_ers],1, sum)
survey$DERS_lack_ec <- apply(DERS[cols_lack_ec],1, sum)
```

#write dfs
```{r}
survey_filtered <- survey  %>%
  subset(self.reportattention==1)

final <- merge(results_recode, survey_filtered,by.x="ID",by.y="Participant.Public.ID.y")

negative_ratings_final <-  merge(negative_ratings, survey_filtered,by.x="Participant.Public.ID",by.y="Participant.Public.ID.y")

positive_ratings_final <-  merge(positive_ratings, survey_filtered,by.x="Participant.Public.ID",by.y="Participant.Public.ID.y")

write.csv(file = '../data/study2final_negativeratings.csv',negative_ratings_final)
write.csv(file = '../data/study2final_positiveratings.csv',positive_ratings_final)

write.csv(file = '../data/study2final_granularityscores.csv',final)
```

